steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/sachinar/codelab"]
    env: ["PROJECT_ROOT=github.com/sachinar/codelab"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/sachin-first/codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/sachin-first/codelab:$REVISION_ID"
